#define DEBUG false

#define CAM_SS 16
#define IR_SS 15
#define ALT_SCK 14
#define CAM_TRANSFER_NUM 6
#define IR_TRANSFER_NUM 4

#define FORWARD_SPEED 100

#define angToRad 0.01745329251
#define radToAng 57.2957795131

#define IMU_ADDRESS 0x68
#define MAG_ADDRESS 0x0C
#define GYRO_FULL_SCALE_2000_DPS 0x18
#define ACC_FULL_SCALE_2_G 0x00
#define IMU_CALIBRATION 500
#define IMU_CALIBRATION_NUM 500
#define IMU_MULTI 1.0
#define GOAL_CUTOFF 60
#define ROTATION_CUTOFF 150

#define BACKSPIN_PIN 0

#define LIGHTGATE_PIN 0
#define LIGHTGATE_THRESHOLD 0
#define KICKER_PIN 0
#define MIN_BALL_CONFIDENCE 0
#define BALL_CONFIDENCE 2

/* Coord Calc */
#define ATTACK_GOAL_Y 0
#define ATTACK_GOAL_X 0
#define DEFENSE_GOAL_Y 0
#define DEFENSE_GOAL_X 0


/* Orbit */
#define BIG_DISTANCE 0.00
#define MED_DISTANCE 0.00
#define SHORT_DISTANCE 0.00
